// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ports/api/store.proto

package api

import (
	model "golang-microservices-demo/protobuf/ports/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamPortsRequest starts streaming ports from the provided file.
type StreamPortsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *StreamPortsRequest) Reset() {
	*x = StreamPortsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_api_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPortsRequest) ProtoMessage() {}

func (x *StreamPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_api_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPortsRequest.ProtoReflect.Descriptor instead.
func (*StreamPortsRequest) Descriptor() ([]byte, []int) {
	return file_ports_api_store_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPortsRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// GetPortResponse defines the response for a getPort call
type StreamPortsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port *model.Port `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *StreamPortsResponse) Reset() {
	*x = StreamPortsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_api_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPortsResponse) ProtoMessage() {}

func (x *StreamPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_api_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPortsResponse.ProtoReflect.Descriptor instead.
func (*StreamPortsResponse) Descriptor() ([]byte, []int) {
	return file_ports_api_store_proto_rawDescGZIP(), []int{1}
}

func (x *StreamPortsResponse) GetPort() *model.Port {
	if x != nil {
		return x.Port
	}
	return nil
}

var File_ports_api_store_proto protoreflect.FileDescriptor

var file_ports_api_store_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x1a, 0x16, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0x3c, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x32, 0x59, 0x0a, 0x05, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x50, 0x0a, 0x0b, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x72,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x72, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ports_api_store_proto_rawDescOnce sync.Once
	file_ports_api_store_proto_rawDescData = file_ports_api_store_proto_rawDesc
)

func file_ports_api_store_proto_rawDescGZIP() []byte {
	file_ports_api_store_proto_rawDescOnce.Do(func() {
		file_ports_api_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_ports_api_store_proto_rawDescData)
	})
	return file_ports_api_store_proto_rawDescData
}

var file_ports_api_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ports_api_store_proto_goTypes = []interface{}{
	(*StreamPortsRequest)(nil),  // 0: ports.api.StreamPortsRequest
	(*StreamPortsResponse)(nil), // 1: ports.api.StreamPortsResponse
	(*model.Port)(nil),          // 2: ports.model.Port
}
var file_ports_api_store_proto_depIdxs = []int32{
	2, // 0: ports.api.StreamPortsResponse.port:type_name -> ports.model.Port
	0, // 1: ports.api.Ports.StreamPorts:input_type -> ports.api.StreamPortsRequest
	1, // 2: ports.api.Ports.StreamPorts:output_type -> ports.api.StreamPortsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ports_api_store_proto_init() }
func file_ports_api_store_proto_init() {
	if File_ports_api_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ports_api_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamPortsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_api_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamPortsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ports_api_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ports_api_store_proto_goTypes,
		DependencyIndexes: file_ports_api_store_proto_depIdxs,
		MessageInfos:      file_ports_api_store_proto_msgTypes,
	}.Build()
	File_ports_api_store_proto = out.File
	file_ports_api_store_proto_rawDesc = nil
	file_ports_api_store_proto_goTypes = nil
	file_ports_api_store_proto_depIdxs = nil
}
